
### GET Pacientes
GET https://api-vollmed-8f1315f3dab6.herokuapp.com/pacientes

### POST Cadastrar Paciente
POST https://api-vollmed-8f1315f3dab6.herokuapp.com/pacientes
Content-Type: application/json

{
	"nome": "Aurora S. Fonseca França",
	"telefone": "8199912345",
	"cpf": "10203040506",
	"email": "aurora.franca@email.com",
	"endereco": {
		"logradouro": "av. Bernado Vieira Melo",
		"bairro": "Candeias",
		"cep": "54444000",
		"numero": "1",
		"complemento": "Apartamento",
		"cidade": "Recife",
		"uf": "PE"
	}
}

### PUT Atualizar Paciente
PUT https://api-vollmed-8f1315f3dab6.herokuapp.com/pacientes
content-Type: application/json

{
        "id": 1,
        "nome": "Aurora S. Fonseca França",
        "endereco": {
             "numero": "2002"
        }
}

### DELETE Deletar Paciente
DELETE https://api-vollmed-8f1315f3dab6.herokuapp.com/pacientes/1
